name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# allow the workflow to push the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history so the action can create/update the gh-pages branch
          fetch-depth: 0
          # keep the token provided to the workflow so downstream steps can push
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build:prod -- --configuration=production --output-path=dist/DatalentWebPage --base-href=/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/DatalentWebPage
          cname: datalentsolutions.com